[package]
name = "pulsectl"
version = "0.1.0"
authors = ["Kristopher Ruzic <krruzic@gmail.com>"]
edition = "2018"

[lib]
name = "pulsectl"
path = "src/lib.rs"

[dependencies]
libpulse-binding = "2.14.0"
